name: quicui
description: >-
  QuicUI - AI-Friendly Server-Driven UI Framework for Flutter.
  Define UIs in JSON, update instantly without app deployment.
version: 1.0.0
homepage: https://github.com/Ikolvi/QuicUI
repository: https://github.com/Ikolvi/QuicUI
issue_tracker: https://github.com/Ikolvi/QuicUI/issues
documentation: https://github.com/Ikolvi/QuicUI/wiki
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management - BLoC Pattern
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  
  # HTTP & API
  dio: ^5.7.0
  http: ^1.2.0
  
  # Local Database (Primary: ObjectBox for performance)
  objectbox: ^4.1.1
  objectbox_flutter_libs: ^4.1.1
  
  # Alternative: Hive (lightweight option)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Serialization
  json_annotation: ^4.8.1
  
  # Backend Integration
  supabase_flutter: ^2.10.3
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.20.0
  cached_network_image: ^3.3.1
  device_info_plus: ^11.1.1
  shared_preferences: ^2.2.3
  
  # Logging
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  objectbox_generator: ^4.3.1
  
  # Testing
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
