name: quicui
description: "Remote dynamic UI for Flutter"
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.0
  get: ^4.6.5
  
  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.0
  
  # Local Database (Primary: ObjectBox)
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  
  # Alternative: Hive (lightweight option)
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  
  # Serialization
  json_serializable: ^6.7.0
  json_annotation: ^4.8.0
  
  # Validation
  validators: ^3.0.0
  
  # Utilities
  uuid: ^4.1.0
  intl: ^0.20.0
  cached_network_image: ^3.3.1
  
  # Logging
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  objectbox_generator: ^4.1.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
