package com.quicui.codepush

import android.util.Log
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.MessageDigest

/**
 * BsDiff patch application for QuicUI Code Push
 * 
 * Applies binary patches generated by the QuicUI compiler to create updated
 * AOT snapshots without requiring full app downloads.
 * 
 * Patch Format (QUICUI01):
 * - Magic: "QUICUI01" (8 bytes)
 * - Old size: int64 (8 bytes)
 * - New size: int64 (8 bytes)
 * - Operation count: int32 (4 bytes)
 * - Old hash: SHA256 hex string (64 bytes)
 * - New hash: SHA256 hex string (64 bytes)
 * - Operations: variable length
 *   - Type: byte (0 = copy, 1 = add)
 *   - Old offset: int64 (8 bytes)
 *   - Length: int32 (4 bytes)
 *   - Data: bytes (only for add operations)
 */
class BsDiffPatcher {
    companion object {
        private const val TAG = "BsDiffPatcher"
        private const val MAGIC = "QUICUI01"
        private const val HEADER_SIZE = 32
        private const val HASH_SIZE = 64
        
        private const val OP_COPY = 0.toByte()
        private const val OP_ADD = 1.toByte()
        
        /**
         * Apply a BsDiff patch to create a new file
         * 
         * @param oldFile Original file (libapp.so from APK)
         * @param patchFile Patch file downloaded from backend
         * @param newFile Output file (patched libapp.so)
         * @return true if successful, false otherwise
         */
        fun applyPatch(oldFile: File, patchFile: File, newFile: File): Boolean {
            return try {
                Log.i(TAG, "Starting BsDiff patch application")
                Log.i(TAG, "Old file: ${oldFile.absolutePath} (${oldFile.length()} bytes)")
                Log.i(TAG, "Patch file: ${patchFile.absolutePath} (${patchFile.length()} bytes)")
                
                // Read files
                val oldBytes = oldFile.readBytes()
                val patchBytes = patchFile.readBytes()
                
                // Parse patch
                val patch = parsePatch(patchBytes)
                Log.i(TAG, "Patch parsed: ${patch.operations.size} operations")
                
                // Validate old file
                val oldHash = sha256(oldBytes)
                if (oldHash != patch.oldHash) {
                    Log.e(TAG, "Old file hash mismatch!")
                    Log.e(TAG, "Expected: ${patch.oldHash}")
                    Log.e(TAG, "Actual: $oldHash")
                    return false
                }
                Log.i(TAG, "Old file hash validated ✓")
                
                // Apply patch
                val newBytes = applyPatchOperations(oldBytes, patch)
                Log.i(TAG, "Patch applied, new size: ${newBytes.size} bytes")
                
                // Validate new file
                val newHash = sha256(newBytes)
                if (newHash != patch.newHash) {
                    Log.e(TAG, "New file hash mismatch!")
                    Log.e(TAG, "Expected: ${patch.newHash}")
                    Log.e(TAG, "Actual: $newHash")
                    return false
                }
                Log.i(TAG, "New file hash validated ✓")
                
                // Write result
                newFile.writeBytes(newBytes)
                Log.i(TAG, "New file written: ${newFile.absolutePath}")
                Log.i(TAG, "BsDiff patch application successful!")
                
                true
            } catch (e: Exception) {
                Log.e(TAG, "Failed to apply BsDiff patch", e)
                false
            }
        }
        
        /**
         * Parse patch file format
         */
        private fun parsePatch(bytes: ByteArray): Patch {
            var offset = 0
            
            // Read and verify magic
            val magic = String(bytes.sliceArray(0 until 8), Charsets.UTF_8)
            if (magic != MAGIC) {
                throw IllegalArgumentException("Invalid patch file: bad magic '$magic'")
            }
            offset += 8
            
            // Read header
            val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
            val oldSize = buffer.getLong(offset)
            offset += 8
            val newSize = buffer.getLong(offset)
            offset += 8
            val opCount = buffer.getInt(offset)
            offset += 4
            
            Log.d(TAG, "Patch header: oldSize=$oldSize, newSize=$newSize, opCount=$opCount")
            
            // Read hashes
            val oldHash = String(bytes.sliceArray(offset until offset + HASH_SIZE), Charsets.UTF_8)
            offset += HASH_SIZE
            val newHash = String(bytes.sliceArray(offset until offset + HASH_SIZE), Charsets.UTF_8)
            offset += HASH_SIZE
            
            // Read operations
            val operations = mutableListOf<PatchOperation>()
            for (i in 0 until opCount) {
                val type = bytes[offset++]
                val oldOffset = buffer.getLong(offset)
                offset += 8
                val length = buffer.getInt(offset)
                offset += 4
                
                val data = if (type == OP_ADD) {
                    bytes.sliceArray(offset until offset + length).also {
                        offset += length
                    }
                } else {
                    null
                }
                
                operations.add(PatchOperation(type, oldOffset, length, data))
            }
            
            return Patch(oldSize, newSize, oldHash, newHash, operations)
        }
        
        /**
         * Apply patch operations to old bytes
         */
        private fun applyPatchOperations(oldBytes: ByteArray, patch: Patch): ByteArray {
            val newBytes = ByteArray(patch.newSize.toInt())
            var newPos = 0
            
            for ((index, op) in patch.operations.withIndex()) {
                when (op.type) {
                    OP_COPY -> {
                        // Copy bytes from old file
                        val oldStart = op.oldOffset.toInt()
                        val oldEnd = oldStart + op.length
                        
                        if (oldEnd > oldBytes.size) {
                            throw IllegalStateException(
                                "Copy operation out of bounds at op $index: " +
                                "trying to copy from $oldStart to $oldEnd, but old size is ${oldBytes.size}"
                            )
                        }
                        
                        System.arraycopy(oldBytes, oldStart, newBytes, newPos, op.length)
                        newPos += op.length
                    }
                    
                    OP_ADD -> {
                        // Add new bytes
                        if (op.data == null) {
                            throw IllegalStateException("Add operation missing data at op $index")
                        }
                        
                        System.arraycopy(op.data, 0, newBytes, newPos, op.length)
                        newPos += op.length
                    }
                    
                    else -> {
                        throw IllegalStateException("Unknown operation type: ${op.type}")
                    }
                }
            }
            
            if (newPos != patch.newSize.toInt()) {
                throw IllegalStateException(
                    "Size mismatch after applying operations: " +
                    "expected ${patch.newSize}, got $newPos"
                )
            }
            
            return newBytes
        }
        
        /**
         * Calculate SHA256 hash of bytes
         */
        private fun sha256(bytes: ByteArray): String {
            val digest = MessageDigest.getInstance("SHA-256")
            val hash = digest.digest(bytes)
            return hash.joinToString("") { "%02x".format(it) }
        }
    }
    
    /**
     * Parsed patch data
     */
    private data class Patch(
        val oldSize: Long,
        val newSize: Long,
        val oldHash: String,
        val newHash: String,
        val operations: List<PatchOperation>
    )
    
    /**
     * Single patch operation
     */
    private data class PatchOperation(
        val type: Byte,
        val oldOffset: Long,
        val length: Int,
        val data: ByteArray?
    )
}
