import 'dart:io';
import 'package:yaml/yaml.dart';
import '../exceptions.dart';

/// QuicUI YAML configuration loader
/// 
/// Automatically loads configuration from quicui.yaml file.
/// This is internal and not exposed in the public API.
class QuicUIYamlConfig {
  final String serverUrl;
  final String? apiKey;
  final String appId;
  final String appName;
  final String currentVersion;
  final List<String> architectures;
  final String compression;
  final bool verbose;
  
  const QuicUIYamlConfig._({
    required this.serverUrl,
    this.apiKey,
    required this.appId,
    required this.appName,
    required this.currentVersion,
    required this.architectures,
    required this.compression,
    required this.verbose,
  });
  
  /// Load configuration from quicui.yaml
  /// 
  /// Searches for quicui.yaml in the following order:
  /// 1. Current directory
  /// 2. Parent directories (up to 5 levels)
  /// 3. Flutter assets (for runtime in app)
  /// 
  /// Throws [QuicUIConfigNotFoundException] if not found.
  /// Throws [QuicUIConfigInvalidException] if configuration is invalid.
  static Future<QuicUIYamlConfig> load({String? configPath}) async {
    final yamlFile = await _findConfigFile(configPath);
    
    if (yamlFile == null) {
      throw QuicUIConfigNotFoundException(configPath);
    }
    
    return _parseYaml(yamlFile);
  }
  
  /// Try to load configuration, returns null if not found
  static Future<QuicUIYamlConfig?> tryLoad({String? configPath}) async {
    try {
      return await load(configPath: configPath);
    } on QuicUIConfigNotFoundException {
      return null;
    }
  }
  
  /// Find quicui.yaml config file
  static Future<File?> _findConfigFile(String? explicitPath) async {
    // If explicit path provided, use it
    if (explicitPath != null) {
      final file = File(explicitPath);
      if (await file.exists()) {
        return file;
      }
      return null;
    }
    
    // Search in current directory and parents
    var directory = Directory.current;
    for (var i = 0; i < 5; i++) {
      final configFile = File('${directory.path}/quicui.yaml');
      if (await configFile.exists()) {
        return configFile;
      }
      
      final parent = directory.parent;
      if (parent.path == directory.path) break;
      directory = parent;
    }
    
    return null;
  }
  
  /// Parse YAML file into QuicUIYamlConfig
  static Future<QuicUIYamlConfig> _parseYaml(File yamlFile) async {
    final content = await yamlFile.readAsString();
    final yaml = loadYaml(content) as YamlMap;
    
    final missingFields = <String>[];
    
    // Parse server configuration
    final server = yaml['server'] as YamlMap?;
    String? serverUrl = server?['url'] as String?;
    String? apiKey = server?['api_key'] as String?;
    
    // Check environment variable for API key override
    final envApiKey = Platform.environment['QUICUI_API_KEY'];
    if (envApiKey != null && envApiKey.isNotEmpty) {
      apiKey = envApiKey;
    }
    
    // API key is required (auto-generated by quicui init)
    if (apiKey == null || apiKey.isEmpty) {
      missingFields.add('server.api_key (run "quicui init" to generate)');
    }
    
    // Check compile-time environment for server URL override
    const envServerUrl = String.fromEnvironment('QUICUI_SERVER_URL');
    if (envServerUrl.isNotEmpty) {
      serverUrl = envServerUrl;
    }
    
    if (serverUrl == null || serverUrl.isEmpty) {
      missingFields.add('server.url');
    }
    
    // Parse app configuration
    final app = yaml['app'] as YamlMap?;
    final appId = app?['id'] as String?;
    final appName = app?['name'] as String? ?? 'QuicUI App';
    
    if (appId == null || appId.isEmpty) {
      missingFields.add('app.id');
    }
    
    // Parse version configuration
    final version = yaml['version'] as YamlMap?;
    final currentVersion = version?['current'] as String? ?? '1.0.0';
    
    // Parse build configuration
    final build = yaml['build'] as YamlMap?;
    final archList = build?['architectures'] as YamlList?;
    final architectures = archList?.map((e) => e.toString()).toList() ?? ['arm64-v8a'];
    
    // Parse patch configuration
    final patch = yaml['patch'] as YamlMap?;
    final compression = patch?['compression'] as String? ?? 'xz';
    
    // Parse advanced configuration
    final advanced = yaml['advanced'] as YamlMap?;
    final verbose = advanced?['verbose'] as bool? ?? false;
    
    // Throw if missing required fields
    if (missingFields.isNotEmpty) {
      throw QuicUIConfigInvalidException(
        'Missing required configuration fields',
        missingFields: missingFields,
      );
    }
    
    return QuicUIYamlConfig._(
      serverUrl: serverUrl!,
      apiKey: apiKey,
      appId: appId!,
      appName: appName,
      currentVersion: currentVersion,
      architectures: architectures,
      compression: compression,
      verbose: verbose,
    );
  }
  
  @override
  String toString() => 'QuicUIYamlConfig(appId: $appId, serverUrl: ${serverUrl.substring(0, 30)}...)';
}
